
- name: Adds generic maps
  template:
    src: generic.j2
    dest: /etc/postfix/generic
    mode: 0640
    owner: postfix
    group: root
  notify: Postmap SMTP generic map

- name: Adds mandrill headers
  template:
    src: mandrill_headers.j2
    dest: /etc/postfix/mandrill_headers
    mode: 0640
    owner: postfix
    group: root
  when: postfix_to_mandrill_subaccount is defined
  notify: Restart postfix
