- name: Adds generic maps
  template:
    src: generic.j2
    dest: /etc/postfix/generic
    mode: 0640
    owner: postfix
    group: root
  notify: Postmap SMTP generic map

- name: Adds mandrill header checks
  template:
    src: header_check.j2
    dest: /etc/postfix/header_check
    mode: 0640
    owner: postfix
    group: root
  notify: Restart postfix
