- name: Installs postfix and mailutils
  apt: pkg={{ item }} state=latest
  with_items:
    - postfix
    - mailutils

- name: Adds main config
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: postfix
    group: root
    mode: 0640
  notify: Restart postfix

- name: Adds SASL config
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: 0640
    owner: postfix
    group: root
  notify: Postmap SASL

- name: Pushes master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    mode: 0640
    owner: postfix
    group: root
  notify: Restart postfix
